# -*- coding: utf-8 -*-
"""world copy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6ooOqvClTd11H_m4EKZ5v_2geqFbzN-
"""

something= input("please enter something: ")
number=int(input("please enter a number: "))
for i in range (number):
    print(something)
